# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book2author',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book2author',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='app01.Author'),
        ),
        migrations.DeleteModel(
            name='Book2Author',
        ),
    ]
